class LocalizerBase():

    def __init__(self) -> None:
        super().__init__()

        # 通用
        self.add: str = "新增"
        self.edit: str = "修改"
        self.none: str = "无"
        self.stop: str = "停止"
        self.start: str = "开始"
        self.close: str = "关闭"
        self.alert: str = "提醒"
        self.warning: str = "警告"
        self.confirm: str = "确认"
        self.cancel: str = "取消"
        self.enable: str = "启用"
        self.disable: str = "禁用"
        self.auto: str = "自动"

        # 日志
        self.log_config_file_not_exist: str = "配置文件不存在 ..."
        self.log_api_test_failure: str = "接口测试失败 ... "
        self.translator_max_round: str = "最大轮次"
        self.translator_current_round: str = "当前轮次"
        self.translator_api_url: str = "接口地址"
        self.translator_name: str = "接口名称"
        self.translator_model: str = "模型名称"
        self.translator_proxy_url: str = "生效中的 网络代理"
        self.translator_prompt: str = "本次任务使用以下提示词：\n{PROMPT}\n"
        self.translator_begin: str = "即将开始执行翻译任务，预计任务总数为 {TASKS}, 并发任务数为 {BATCH_SIZE}，请注意保持网络通畅 ..."
        self.translator_writing: str = "正在写入翻译数据，等稍候 ..."
        self.translator_done: str = "所有文本均已翻译，翻译任务已结束 ..."
        self.translator_failure: str = "已到最大翻译轮次，仍有部分文本未翻译，请检查翻译结果 ..."
        self.translator_stop: str = "翻译任务已停止 ..."
        self.translator_generate_task: str = "生成翻译任务"
        self.translator_rule_filter: str = "规则过滤已完成，共过滤 {COUNT} 个无需翻译的条目 ..."
        self.translator_mtool_filter: str = "MToolOptimizer 预处理已完成，共过滤 {COUNT} 个包含重复子句的条目 ..."
        self.translator_language_filter: str = "语言过滤已完成，共过滤 {COUNT} 个不包含目标语言的条目 ..."
        self.translator_task_response_think: str = "模型思考内容：\n"
        self.translator_task_response_result: str = "模型回复内容：\n"
        self.translator_task_failure: str = "译文文本未通过检查，将在下一轮次的翻译中自动重试"
        self.translator_task_failure_few: str = "部分译文文本未通过检查，将在下一轮次的翻译中自动重试"
        self.translator_task_success: str = "任务耗时 {TIME} 秒，文本行数 {LINES} 行，输入消耗 {PT} Tokens，输出消耗 {CT} Tokens"
        self.file_checker_code: str = "已完成代码检查，未发现异常条目 ..."
        self.file_checker_glossary: str = "已完成术语表检查，未发现异常条目 ..."
        self.file_checker_translation: str = "已完成翻译状态检查，未发现异常条目 ..."

        # 主页面
        self.app_fluent_window_debug_msg: str = "调试模式已启用 ..."
        self.app_fluent_window_close_message_box_content: str = "确定是否退出程序 ... ？"
        self.app_fluent_window_close_message_box_msg: str = "主窗口已关闭，稍后应用将自动退出 ..."
        self.app_fluent_window_language_message_box_content: str = "请选择应用语言，新的语言设置将在下次启动时生效！\nSelect application language, Changes will take effect on restart!"
        self.app_fluent_window_language_message_box_msg: str = "应用语言切换成功，请重启应用生效 ...\nLanguage switched successfully, Please restart the application for changes to take effect..."
        self.app_fluent_window_theme_btn: str = "变换自如"
        self.app_fluent_window_language_btn: str = "字字珠玑"
        self.app_fluent_window_app_settings_page: str = "应用设置"
        self.app_fluent_window_platform_page: str = "接口管理"
        self.app_fluent_window_prject_page: str = "项目设置"
        self.app_fluent_window_translation_page: str = "开始翻译"
        self.app_fluent_window_basic_settings_page: str = "基础设置"
        self.app_fluent_window_advance_Feature_page: str = "高级功能"
        self.app_fluent_window_prompt_dictionary_page: str = "术语表"
        self.app_fluent_window_replcae_before_translation_page: str = "译前替换"
        self.app_fluent_window_replcae_after_translation_page: str = "译后替换"
        self.app_fluent_window_custom_prompt_navigation_item: str = "自定义提示词"
        self.app_fluent_window_custom_prompt_zh_page: str = "中文版本"
        self.app_fluent_window_custom_prompt_en_page: str = "英文版本"

        # 应用设置
        self.app_settings_page_proxy_url = "请输入网络代理地址 ..."
        self.app_settings_page_proxy_url_title = "网络代理地址"
        self.app_settings_page_proxy_url_content = "启用该功能后，将使用设置的代理地址向接口发送请求，例如 http://127.0.0.1:7890"
        self.app_settings_page_font_hinting_title = "应用字体优化"
        self.app_settings_page_font_hinting_content = "启用此功能后，字体的边缘渲染将更加圆润（将在应用重启后生效）"
        self.app_settings_page_debug_title = "调试模式"
        self.app_settings_page_debug_content = "启用此功能后，应用将显示额外的调试信息"
        self.app_settings_page_scale_factor_title = "全局缩放比例"
        self.app_settings_page_scale_factor_content = "启用此功能后，应用界面将按照所选比例进行缩放（将在应用重启后生效）"

        # 接口管理
        self.platform_page_api_test_doing: str = "接口测试正在执行中，请稍后再试 ..."
        self.platform_page_api_test_result: str = "接口测试结果：成功 {SUCCESS} 个，失败 {FAILURE} 个 ..."
        self.platform_page_api_activate: str = "激活接口"
        self.platform_page_api_edit: str = "编辑接口"
        self.platform_page_api_args: str = "编辑参数"
        self.platform_page_api_test: str = "测试接口"
        self.platform_page_api_delete: str = "删除接口"
        self.platform_page_widget_add_title: str = "接口列表"
        self.platform_page_widget_add_content: str = "在此添加和管理任何兼容 OpenAI、Anthropic 格式的 LLM 模型接口"

        # 接口编辑
        self.platform_edit_page_widget_name: str = "请输入接口名称 ..."
        self.platform_edit_page_widget_name_title: str = "接口名称"
        self.platform_edit_page_widget_name_content: str = "请输入接口名称，仅用于应用内显示，无实际作用"
        self.platform_edit_page_widget_api_url: str = "请输入接口地址 ..."
        self.platform_edit_page_widget_api_url_title: str = "接口地址"
        self.platform_edit_page_widget_api_url_content: str = "请输入接口地址，请注意辨别结尾是否需要添加 /v1"
        self.platform_edit_page_widget_api_key: str = "请输入接口密钥 ..."
        self.platform_edit_page_widget_api_key_title: str = "接口密钥"
        self.platform_edit_page_widget_api_key_content: str = "请输入接口密钥，例如 sk-d0daba12345678fd8eb7b8d31c123456，填入多个密钥可以轮询使用，每行一个"
        self.platform_edit_page_widget_api_format_title: str = "接口格式"
        self.platform_edit_page_widget_api_format_content: str = "请选择接口格式，大部分平台兼容 OpenAI 格式，部分平台的 Claude 模型则使用 Anthropic 格式"
        self.platform_edit_page_widget_model: str = "请输入模型名称 ..."
        self.platform_edit_page_widget_model_title: str = "模型名称"
        self.platform_edit_page_widget_model_content: str = "当前使用的模型为 {MODEL}"
        self.platform_edit_page_widget_model_edit: str = "手动输入"
        self.platform_edit_page_widget_model_sync: str = "在线获取"

        # 参数编辑
        self.args_edit_page_widget_top_p_title: str = "top_p"
        self.args_edit_page_widget_top_p_content: str = "请谨慎设置，错误的值可能导致结果异常或者请求报错"
        self.args_edit_page_widget_temperature_title: str = "temperature"
        self.args_edit_page_widget_temperature_content: str = "请谨慎设置，错误的值可能导致结果异常或者请求报错"
        self.args_edit_page_widget_presence_penalty_title: str = "presence_penalty"
        self.args_edit_page_widget_presence_penalty_content: str = "请谨慎设置，错误的值可能导致结果异常或者请求报错"
        self.args_edit_page_widget_frequency_penalty_title: str = "frequency_penalty"
        self.args_edit_page_widget_frequency_penalty_content: str = "请谨慎设置，错误的值可能导致结果异常或者请求报错"
        self.args_edit_page_document_link: str = "点击查看文档"

        # 模型列表
        self.model_list_page_widget_title: str = "可用的模型列表"
        self.model_list_page_widget_content: str = "点击选择要使用的模型"
        self.model_list_page_widget_failure: str = "获取模型列表失败，请检查接口配置 ..."

        # 项目设置
        self.project_page_widget_source_language_title: str = "原文语言"
        self.project_page_widget_source_language_content: str = "设置当前翻译项目所使用的原文文本的语言"
        self.project_page_widget_source_language_items: str = "中文,英文,日文,韩文,俄文"
        self.project_page_widget_target_language_title: str = "译文语言"
        self.project_page_widget_target_language_content: str = "设置当前翻译项目所使用的译文文本的语言"
        self.project_page_widget_target_language_items: str = "中文,英文,日文,韩文,俄文"
        self.project_page_widget_input_folder_title: str = "输入文件夹"
        self.project_page_widget_input_folder_content: str = "当前输入文件夹为"
        self.project_page_widget_input_folder_btn: str = "选择文件夹"
        self.project_page_widget_output_folder_title: str = "输出文件夹（不能与输入文件夹相同）"
        self.project_page_widget_output_folder_content: str = "当前输出文件夹为"
        self.project_page_widget_output_folder_btn: str = "选择文件夹"
        self.project_page_widget_traditional_chinese_title: str = "使用繁体输出中文"
        self.project_page_widget_traditional_chinese_content: str = "启用此功能后，在译文语言设置为中文时，将使用繁体字形输出中文文本"

        # 开始翻译
        self.translation_page_status_idle = "无任务"
        self.translation_page_status_api_testing = "测试中"
        self.translation_page_status_translating = "翻译中"
        self.translation_page_status_stoping = "停止中"
        self.translation_page_indeterminate_saving = "缓存文件保存中 ..."
        self.translation_page_indeterminate_stoping = "正在停止翻译任务 ..."
        self.translation_page_card_time = "累计时间"
        self.translation_page_card_remaining_time = "剩余时间"
        self.translation_page_card_line = "翻译行数"
        self.translation_page_card_remaining_line = "剩余行数"
        self.translation_page_card_speed = "平均速度"
        self.translation_page_card_token = "累计消耗"
        self.translation_page_card_task = "实时任务数"
        self.translation_page_alert_start = "将重置尚未完成的翻译任务，是否确认开始新的翻译任务 ... ？"
        self.translation_page_alert_pause = "停止的翻译任务可以随时继续翻译，是否确定停止任务 ... ？"
        self.translation_page_continue = "继续翻译"
        self.translation_page_export = "导出翻译数据"
        self.translation_page_export_toast = "已根据当前的翻译数据在输出文件夹下生成翻译文件 ..."

        # 基础设置
        self.basic_settings_page_batch_size_title = "并发任务数"
        self.basic_settings_page_batch_size_content = "同时执行的翻译任务的最大数量，合理设置可以极大的增加翻译速度，请参考接口平台的限制进行设置，本地接口无需设置"
        self.basic_settings_page_task_token_limit_title = "翻译任务长度阈值"
        self.basic_settings_page_task_token_limit_content = "每个翻译任务一次性向模型发送的文本长度的最大值，单位为 Token"
        self.basic_settings_page_request_timeout_title = "请求超时时间"
        self.basic_settings_page_request_timeout_content = "翻译任务发起请求时等待模型回复的最长时间，超时仍未收到回复，则会判断为任务失败，单位为秒，不支持"
        self.basic_settings_page_max_round_title = "翻译流程最大轮次"
        self.basic_settings_page_max_round_content = "当完成一轮翻译后，如果还有未翻译的条目，将重新开始新的翻译流程，直到翻译完成或者达到最大轮次"

        # 高级功能
        self.advance_feature_page_auto_glossary_enable_title = "自动补全术语表（实验性功能，不支持 SakuraLLM 模型）"
        self.advance_feature_page_auto_glossary_enable_content = (
            "启用此功能后，在翻译的同时将对文本进行分析，尝试自动补全术语表中缺失的专有名词条目。"
            + "\n" + "此功能设计目的仅为查漏补缺，并不能代替手动制作的术语表，只有在 **启用术语表功能** 时才生效。"
            + "\n" + "可能导致 **负面效果** 或 **翻译异常**，理论上只有在 DeepSeek V3/R1 等强力模型上才会有正面效果，请 **自行判断** 是否启用。"
        )
        self.advance_feature_page_mtool_optimizer_enable_title = "MTool 优化器"
        self.advance_feature_page_mtool_optimizer_enable_content = (
            "启用此功能后，在对 MTool 文本进行翻译时，至多可减少 40% 的 翻译时间 与 Token 消耗。"
            + "\n" + "可能导致 **原文残留** 或 **语句不连贯** 等问题，请 **自行判断** 是否启用，并且只应在 **翻译 MTool 文本时** 启用。"
        )

        # 术语表
        self.glossary_page_head_title = "术语表"
        self.glossary_page_head_content = "通过在提示词中构建术语表来引导模型翻译，可实现统一翻译、矫正人称属性等功能"
        self.glossary_page_table_row_01 = "原文"
        self.glossary_page_table_row_02 = "译文"
        self.glossary_page_table_row_03 = "描述"
        self.glossary_page_import = "导入"
        self.glossary_page_import_toast = "数据已导入 ..."
        self.glossary_page_export = "导出"
        self.glossary_page_export_path = "导出_术语表.json"
        self.glossary_page_export_toast = "数据已导出到应用根目录 ..."
        self.glossary_page_add = "添加"
        self.glossary_page_add_toast = "新行已添加 ..."
        self.glossary_page_save = "保存"
        self.glossary_page_save_toast = "数据已保存 ..."
        self.glossary_page_reset = "重置"
        self.glossary_page_reset_toast = "数据已重置 ..."
        self.glossary_page_reset_alert = "是否确认重置为默认数据 ... ？"
        self.glossary_page_kg = "一键制作工具"
        self.glossary_page_wiki = "功能说明"

        # 译前替换
        self.replace_before_translation_page_head_title = "译前替换"
        self.replace_before_translation_page_head_content = (
            "在翻译开始前，将原文中匹配的部分替换为指定的文本，执行的顺序为从上到下依次替换"
            + "\n" + "翻译 RPGMaker MV/MZ 游戏时，导入 data 或 www\\data 文件夹内的 Actors.json 文件可以显著提升翻译质量"
        )
        self.replace_before_translation_page_table_row_01 = "原文"
        self.replace_before_translation_page_table_row_02 = "替换"
        self.replace_before_translation_page_import = "导入"
        self.replace_before_translation_page_import_toast = "数据已导入 ..."
        self.replace_before_translation_page_export = "导出"
        self.replace_before_translation_page_export_path = "导出_译前替换.json"
        self.replace_before_translation_page_export_toast = "数据已导出到应用根目录 ..."
        self.replace_before_translation_page_add = "添加"
        self.replace_before_translation_page_add_toast = "新行已添加 ..."
        self.replace_before_translation_page_save = "保存"
        self.replace_before_translation_page_save_toast = "数据已保存 ..."
        self.replace_before_translation_page_reset = "重置"
        self.replace_before_translation_page_reset_toast = "数据已重置 ..."
        self.replace_before_translation_page_reset_alert = "是否确认重置为默认数据 ... ？"
        self.replace_before_translation_page_wiki = "功能说明"

        # 译后替换
        self.replace_after_translation_page_head_title = "译后替换"
        self.replace_after_translation_page_head_content = "在翻译完成后，将译文中匹配的部分替换为指定的文本，执行的顺序为从上到下依次替换"
        self.replace_after_translation_page_table_row_01 = "原文"
        self.replace_after_translation_page_table_row_02 = "替换"
        self.replace_after_translation_page_import = "导入"
        self.replace_after_translation_page_import_toast = "数据已导入 ..."
        self.replace_after_translation_page_export = "导出"
        self.replace_after_translation_page_export_path = "导出_译前替换.json"
        self.replace_after_translation_page_export_toast = "数据已导出到应用根目录 ..."
        self.replace_after_translation_page_add = "添加"
        self.replace_after_translation_page_add_toast = "新行已添加 ..."
        self.replace_after_translation_page_save = "保存"
        self.replace_after_translation_page_save_toast = "数据已保存 ..."
        self.replace_after_translation_page_reset = "重置"
        self.replace_after_translation_page_reset_toast = "数据已重置 ..."
        self.replace_after_translation_page_reset_alert = "是否确认重置为默认数据 ... ？"
        self.replace_after_translation_page_wiki = "功能说明"

        # 自定义提示词 - 中文
        self.custom_prompt_zh_page_head_title = "译文语言设置为中文时使用的自定义提示词（不支持 SakuraLLM 模型）"
        self.custom_prompt_zh_page_head_content = (
            "通过自定义提示词追加故事设定、行文风格等额外翻译要求。"
            + "\n" + "注意：前缀、后缀部分固定不可修改，只有 **译文语言设置为中文时** 才会使用本页中的自定义提示词。"
        )
        self.custom_prompt_zh_page_save = "保存"
        self.custom_prompt_zh_page_save_toast = "数据已保存 ..."
        self.custom_prompt_zh_page_reset = "重置"
        self.custom_prompt_zh_page_reset_toast = "数据已重置 ..."

        # 自定义提示词 - 英文
        self.custom_prompt_en_page_head_title = "译文语言设置为非中文时使用的自定义提示词（不支持 SakuraLLM 模型）"
        self.custom_prompt_en_page_head_content = (
            "通过自定义提示词追加故事设定、行文风格等额外翻译要求。"
            + "\n" + "注意：前缀、后缀部分固定不可修改，只有 **译文语言设置为非中文时** 才会使用本页中的自定义提示词。"
        )
        self.custom_prompt_en_page_save = "保存"
        self.custom_prompt_en_page_save_toast = "数据已保存 ..."
        self.custom_prompt_en_page_reset = "重置"
        self.custom_prompt_en_page_reset_toast = "数据已重置 ..."